services:
  app:
    build: .
    restart: unless-stopped
    # container_name: app
    ports:
      - 8105-8106:8005
    networks:
      example-network:
        # ipv4_address: 172.16.238.10

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9190:9090
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      example-network:
        # ipv4_address: 172.16.238.11
        
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "472"
    depends_on:
      - prometheus    
    ports:
      - 3100:3000
    restart: unless-stopped
    env_file:
      - ./config.monitoring
    volumes:
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    networks:
      example-network:
        # ipv4_address: 172.16.238.12

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - 9170:9100
    restart: unless-stopped      
    networks:
      example-network:
        # ipv4_address: 172.16.238.13

networks:
  example-network:
    # name: example-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
