name: Loan_prediction
channels:
- defaults

dependencies:
- python=3.12.4
- pip<=24.2
- pip:
  - mlflow==2.15.1
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.1
  - pyyaml==6.0.2
  - scikit-learn==1.5.1
  - scipy==1.14.1
    